title: Schuetzen Park
email: exner@duck.com
description: > # this means to ignore newlines until "baseurl:"
  One of Nature's Fairest Spots
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  schuetzenpark

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  load_paths:
    - _sass
    - node_modules
exclude: 
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
